-- Run once if `dr_training_leads` exists without profile/question columns.
-- Ignore "Duplicate column" errors if a column already exists.

ALTER TABLE dr_training_leads ADD COLUMN ProfileSummary TEXT NULL COMMENT 'natural-language summary of the lead profile generated by Bedrock or template';
ALTER TABLE dr_training_leads ADD COLUMN TargetingQuestions TEXT NULL COMMENT 'JSON array of 5 targeting question-and-answer pairs generated by Bedrock or template';
ALTER TABLE dr_training_leads ADD COLUMN IsProfileGenerated TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'dr_profile_generation_status.code: 0 pending, 1 template, 2 bedrock, 3 other fallback';